//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public short RegisterId { get; set; }
        public short BookId { get; set; }
        public short UserId { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<System.DateTime> ExpectedDate { get; set; }
        public Nullable<System.DateTime> ActualReturnDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
